/*
 * llminference.h — C-ABI bindings for llminference.
 *
 * Auto-generated by cbindgen from swe-inference-ffi. Do not edit by hand.
 */

#ifndef LLMINFERENCE_H
#define LLMINFERENCE_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Error codes returned by every function. Zero is success.
 */
typedef enum LlmError {
  OK = 0,
  /**
   * A pointer argument was null or a string wasn't valid UTF-8.
   */
  INVALID_INPUT = 1,
  /**
   * Config load, model download, or weight load failed.
   */
  LOAD_FAILED = 2,
  /**
   * Tokenization or generation returned an error.
   */
  RUNTIME = 3,
  /**
   * A Rust panic was caught at the FFI boundary.
   */
  PANIC = 4,
  /**
   * Internal error (should not happen in normal operation).
   */
  INTERNAL = 5,
  /**
   * The handle was destroyed (via `llminference_destroy`). Any call that
   * observes this should treat the handle as gone and not retry.
   */
  DESTROYED = 6,
} LlmError;

/**
 * Opaque session handle. Returned by `llminference_init`, consumed by the
 * other functions, freed by `llminference_destroy`.
 *
 * The actual layout is private and may change between versions. The
 * handle pointer remains valid for the lifetime of the process after
 * init — destroy releases the inner model but not the outer struct, so
 * any stray pointer use returns `Destroyed` rather than segfaulting.
 */
typedef struct LlmHandle LlmHandle;

/**
 * Callback invoked for each generated token. Receives:
 *
 * - `piece`: NUL-terminated UTF-8 string, the decoded token text.
 *   Valid ONLY for the duration of this callback — copy it if you need
 *   to keep it.
 * - `user_data`: the opaque pointer passed to `llminference_complete_stream`.
 *
 * Return `true` to keep generating, `false` to stop early. Panics in
 * the callback are caught and converted to "stop generation."
 */
typedef bool (*LlmTokenCallback)(const char *piece, void *user_data);

/**
 * Load the model specified by `application.toml` (found via the
 * standard XDG search path). Writes an opaque handle to `*out_handle`
 * on success.
 *
 * # Safety
 * `out_handle` must point to writable memory holding a pointer.
 */
 int llminference_init(struct LlmHandle **out_handle);

/**
 * Destroy a handle: drops the inner model, releasing weights and
 * activations. Idempotent — calling destroy twice is a safe no-op.
 * Safe to call concurrently with in-flight ops: waits for them to
 * finish, then transitions atomically. Subsequent calls on the handle
 * return `LlmError::Destroyed`.
 *
 * # Safety
 * `handle` must be a pointer returned by `llminference_init`. Passing null
 * is a safe no-op. The handle pointer itself remains valid after this
 * call — only the inner model is released.
 */
 void llminference_destroy(struct LlmHandle *handle);

/**
 * Run a single completion: prompt in, generated text out.
 *
 * Applies the model's chat template (wraps the prompt as a user message).
 * `max_tokens = 0` means use the model's default context length.
 * `temperature = 0.0` means greedy sampling.
 *
 * On success, writes a pointer to a NUL-terminated UTF-8 string to
 * `*out_text`. The caller must free it via `llminference_free_string`.
 *
 * # Safety
 * `handle` is a valid handle from `llminference_init`. `prompt` is a
 * NUL-terminated UTF-8 string. `out_text` points to writable memory.
 */

int llminference_complete(const struct LlmHandle *handle,
                          const char *prompt,
                          uint32_t max_tokens,
                          float temperature,
                          char **out_text);

/**
 * Run a single completion with the model's chat template applied.
 *
 * Wraps `prompt` as a user message and calls the generator's templated
 * path — equivalent to the daemon's `/v1/chat/completions` endpoint.
 * Use this when you want the model's chat-tuned behavior; use
 * `llminference_complete` when you want raw prefix continuation.
 *
 * Otherwise identical to `llminference_complete`: blocking, returns full
 * text, caller frees with `llminference_free_string`.
 *
 * # Safety
 * Same as `llminference_complete`.
 */

int llminference_complete_chat(const struct LlmHandle *handle,
                               const char *prompt,
                               uint32_t max_tokens,
                               float temperature,
                               char **out_text);

/**
 * Streaming completion: calls `callback` for each generated token as
 * it's decoded. Blocks until the generator stops (EOS, max_tokens,
 * or callback returned `false`).
 *
 * `max_tokens = 0` means use the model's default context length.
 * `temperature = 0.0` means greedy sampling.
 *
 * # Safety
 * `handle` is a valid handle from `llminference_init`. `prompt` is a
 * NUL-terminated UTF-8 string. `callback` is a function pointer that
 * remains valid for the duration of this call. `user_data` is opaque
 * to this library and passed through unchanged.
 */

int llminference_complete_stream(const struct LlmHandle *handle,
                                 const char *prompt,
                                 uint32_t max_tokens,
                                 float temperature,
                                 LlmTokenCallback callback,
                                 void *user_data);

/**
 * Compute a mean-pooled embedding for the given input text. On success,
 * writes a pointer to an f32 array of length `*out_dim` to `*out_vec`.
 * The caller must free it via `llminference_free_floats`.
 *
 * # Safety
 * See `llminference_complete`.
 */

int llminference_embed(const struct LlmHandle *handle,
                       const char *text,
                       float **out_vec,
                       uintptr_t *out_dim);

/**
 * Tokenize `text` and write the token ids to `*out_ids`, length in
 * `*out_len`. The caller must free via `llminference_free_u32s`.
 *
 * # Safety
 * See `llminference_complete`.
 */

int llminference_tokenize(const struct LlmHandle *handle,
                          const char *text,
                          uint32_t **out_ids,
                          uintptr_t *out_len);

/**
 * Return just the token count for `text` (cheap — no allocation
 * returned to the caller). IDE plugins call this on every keystroke.
 *
 * # Safety
 * See `llminference_complete`.
 */

int llminference_token_count(const struct LlmHandle *handle,
                             const char *text,
                             uintptr_t *out_count);

/**
 * Free a string returned by `llminference_complete`. Passing null is a no-op.
 *
 * # Safety
 * `s` must be a pointer previously returned by `llminference_complete`.
 */
 void llminference_free_string(char *s);

/**
 * Free an f32 array returned by `llminference_embed`. Passing null is a no-op.
 *
 * # Safety
 * `p` must be a pointer returned by `llminference_embed` and `len` must be
 * the exact length written to `*out_dim` at that time.
 */
 void llminference_free_floats(float *p, uintptr_t len);

/**
 * Free a u32 array returned by `llminference_tokenize`. Passing null is a no-op.
 *
 * # Safety
 * `p` must be a pointer returned by `llminference_tokenize` and `len` must
 * be the exact length written to `*out_len` at that time.
 */
 void llminference_free_u32s(uint32_t *p, uintptr_t len);

#endif  /* LLMINFERENCE_H */
